fix: Documentation link
canonical/awsmp pull request #22
Opened 2024-09-12 16:49 UTC by JessicaJang

Documentation link was not linked correctly.

2024-09-12 19:36 UTC, a-dubs requested changes

2024-09-12 19:36 UTC, a-dubs commented on README.rst
> +The documentation can be found https://canonical-awsmp.readthedocs-hosted.com/.
```suggestion
The documentation can be found at: https://canonical-awsmp.readthedocs-hosted.com/.
```
Can't believe i'm nitting a one liner lol

2024-09-16 20:37 UTC, a-dubs approved these changes
Yay 🙌🙌

2024-09-16 21:31 UTC, rpocase approved these changes

2024-09-16 22:56 UTC, merged